package ru.portretnyy.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-06-01T21:18:52.823+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "HelloServiceImplService",
                  wsdlLocation = "http://localhost:8080/HelloService?wsdl",
                  targetNamespace = "http://service.portretnyy.ru/")
public class HelloServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.portretnyy.ru/", "HelloServiceImplService");
    public final static QName RuPortretnyyServiceHelloServicePort = new QName("http://service.portretnyy.ru/", "ru.portretnyy.service.HelloServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/HelloService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/HelloService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RuPortretnyyServiceHelloService
     */
    @WebEndpoint(name = "ru.portretnyy.service.HelloServicePort")
    public RuPortretnyyServiceHelloService getRuPortretnyyServiceHelloServicePort() {
        return super.getPort(RuPortretnyyServiceHelloServicePort, RuPortretnyyServiceHelloService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuPortretnyyServiceHelloService
     */
    @WebEndpoint(name = "ru.portretnyy.service.HelloServicePort")
    public RuPortretnyyServiceHelloService getRuPortretnyyServiceHelloServicePort(WebServiceFeature... features) {
        return super.getPort(RuPortretnyyServiceHelloServicePort, RuPortretnyyServiceHelloService.class, features);
    }

}
