package ru.portretnyy.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-06-01T21:18:52.791+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.portretnyy.ru/", name = "ru.portretnyy.service.HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface RuPortretnyyServiceHelloService {

    @WebMethod
    @Action(input = "http://service.portretnyy.ru/ru.portretnyy.service.HelloService/getTestRequest", output = "http://service.portretnyy.ru/ru.portretnyy.service.HelloService/getTestResponse")
    @RequestWrapper(localName = "getTest", targetNamespace = "http://service.portretnyy.ru/", className = "ru.portretnyy.service.GetTest")
    @ResponseWrapper(localName = "getTestResponse", targetNamespace = "http://service.portretnyy.ru/", className = "ru.portretnyy.service.GetTestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getTest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
